#!/usr/bin/env node
/*
 * Refreshes assets/js/latest.js with the channel's newest uploads and stats.
 * Run by .github/workflows/update-content.yml on a schedule; no dependencies (Node 20+).
 *
 *   node scripts/update-content.mjs           write only when something worth committing changed
 *   node scripts/update-content.mjs --force   always write
 *
 * Data source:
 *   - YT_API_KEY set  -> YouTube Data API (every upload, video lengths, subscriber count)
 *   - otherwise       -> YouTube's public feed (latest 15 uploads; flaky, so it is retried)
 * If the API call fails, the feed is used as a fallback.
 *
 * The file is cumulative: uploads seen on earlier runs are kept. Hand-written entries in
 * assets/js/data.js always win over what is generated here.
 *
 * Fetched values are checked before they replace existing ones (see "checks" below): bad data is
 * skipped, and implausible changes are held back until a second run confirms them.
 */
import { appendFile, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const CHANNEL_ID = "UCgoQsdo_pCiMFXgmdwj031A";
const OUT = fileURLToPath(new URL("../assets/js/latest.js", import.meta.url));
const API_KEY = (process.env.YT_API_KEY || "").trim();
const FORCE = process.argv.includes("--force");
const STATS_REFRESH_DAYS = 1; // with no new uploads, skip the write if stats were already refreshed today
const UA = "Mozilla/5.0 (compatible; ayjlabs-site-updater; +https://ayjtech.github.io/)";

const HEADER =
  "/* AUTO-GENERATED by scripts/update-content.mjs. Do not edit by hand: changes are overwritten.\n" +
  " * To customise a video or Short, copy it into data.js (entries there win over these). */\n";

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const warn = (msg) => console.log(`::warning::${msg}`);

/* ------------------------------------------------------------------ fetch */
async function fetchText(url, { tries = 1, headers = {} } = {}) {
  let last = "";
  for (let i = 1; i <= tries; i++) {
    try {
      const res = await fetch(url, { headers: { "User-Agent": UA, "Accept-Language": "en-US,en;q=0.9", ...headers } });
      if (res.ok) return await res.text();
      last = `HTTP ${res.status}`;
    } catch (e) {
      last = e.message;
    }
    if (i < tries) await sleep(Math.min(15000, 1500 * i));
  }
  throw new Error(last);
}

/* --------------------------------------------------------------- parsing */
function decodeXml(s) {
  return s
    .replace(/&#x([0-9a-f]+);/gi, (_, h) => String.fromCodePoint(parseInt(h, 16)))
    .replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(+d))
    .replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&apos;/g, "'").replace(/&amp;/g, "&");
}
function tag(xml, re) {
  const m = xml.match(re);
  return m ? decodeXml(m[1]) : "";
}
function parseFeed(xml) {
  const out = [];
  for (const m of xml.matchAll(/<entry>([\s\S]*?)<\/entry>/g)) {
    const e = m[1];
    const id = tag(e, /<yt:videoId>([^<]+)</);
    if (!id || tag(e, /<yt:channelId>([^<]+)</) !== CHANNEL_ID) continue; // only this channel's uploads
    out.push({
      id,
      rawTitle: tag(e, /<title>([\s\S]*?)<\/title>/),
      description: tag(e, /<media:description>([\s\S]*?)<\/media:description>/),
      date: tag(e, /<published>([^<]+)</).slice(0, 10),
      isShort: /<link[^>]+href="[^"]*\/shorts\//.test(e),
      views: num(tag(e, /<media:statistics[^>]*views="(\d+)"/)),
      likes: num(tag(e, /<media:starRating[^>]*count="(\d+)"/)),
    });
  }
  return out;
}
function num(v) {
  const n = Number(v);
  return v !== "" && v != null && Number.isFinite(n) ? n : undefined;
}

// "What Fires a Flash ⚡ | How a Capacitor Works #electronics" -> { title, topic }
function splitTitle(raw, isShort) {
  const clean = raw.replace(/#[\p{L}\p{N}_]+/gu, " ").replace(/\s+/g, " ").trim();
  let [title, ...rest] = clean.split(/\s+\|\s+/);
  let topic = rest.join(" | ").trim();
  if (!isShort) {
    title = title.replace(/^how to make\s+(an?\s+)?/i, "");
    title = title.charAt(0).toUpperCase() + title.slice(1);
  }
  return { title: title.trim() || clean, topic };
}
function slugify(s) {
  return s.normalize("NFKD").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 60) || "video";
}
function isoToLength(iso) {
  const m = /^PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?$/.exec(iso || "");
  if (!m) return "";
  const h = +(m[1] || 0), min = +(m[2] || 0), s = +(m[3] || 0);
  const ss = String(s).padStart(2, "0");
  return h ? `${h}:${String(min).padStart(2, "0")}:${ss}` : `${min}:${ss}`;
}

// Maps a parts-list line to a Parts Bin key from data.js (first match wins).
const PART_KEYS = [
  [/ne\s*555|\b555\b/i, "NE555"], [/ca\s*3130/i, "CA3130"], [/\b4017\b/i, "4017"],
  [/bc\s*547/i, "BC547"], [/bc\s*548/i, "BC548"], [/bc\s*557/i, "BC557"], [/2n\s*3904/i, "2N3904"],
  [/tsop/i, "TSOP1738"], [/\bldr\b|light dependent/i, "LDR"], [/microphone|\bmic\b/i, "MIC"],
  [/variable resistor|potentiometer|preset|trimpot/i, "POT"],
  [/resistor|\d\s*(k|m)?\s*(Ω|ohm)/i, "RESISTOR"], [/capacitor|\d\s*(u|µ|μ|n|p)f\b/i, "CAPACITOR"],
  [/\bleds?\b|light emitting/i, "LED"], [/1n\s*400\d|\bin\s*400\d|diode/i, "DIODE"],
  [/buzzer|siren/i, "BUZZER"], [/laser/i, "LASER"], [/relay/i, "RELAY"], [/switch/i, "SWITCH"],
  [/9\s*v\s*battery|battery clip/i, "BATTERY"], [/power (supply|source)/i, "SUPPLY"],
  [/breadboard/i, "BREADBOARD"], [/wire/i, "WIRE"],
];
function parseParts(desc) {
  const lines = desc.split(/\r?\n/);
  const start = lines.findIndex((l) => /(things|parts|components|materials)\b.*\b(need|required|list)|you(?:'ll| will)? need/i.test(l));
  const bullets = [];
  for (const l of lines.slice(Math.max(0, start))) {
    const m = /^\s*[*•·\-–]\s*(.+?)\s*$/.exec(l);
    if (m) bullets.push(m[1]);
    else if (bullets.length && l.trim() && start >= 0) break; // list ended
  }
  if (bullets.length < (start >= 0 ? 1 : 3)) return undefined;
  return bullets.map((b) => {
    let q = 1;
    const qm = /\(?\s*[x×]\s*(\d+)\s*\)?\s*$/i.exec(b);
    if (qm) { q = +qm[1]; b = b.slice(0, qm.index).trim(); }
    const part = { q, n: b };
    const hit = PART_KEYS.find(([re]) => re.test(b));
    if (hit) part.k = hit[1];
    return part;
  });
}
function summarize(desc) {
  const keep = [];
  for (const raw of desc.split(/\r?\n/)) {
    const l = raw.trim();
    if (!l) { if (keep.length) break; continue; }
    if (/^[*•·\-–]\s/.test(l) || /^#\w/.test(l) || /https?:\/\//i.test(l)) break;
    if (/(things|parts|components|materials)\b.*\b(need|required|list)/i.test(l)) break;
    keep.push(l);
  }
  let text = keep.join(" ").replace(/#[\p{L}\p{N}_]+/gu, "").replace(/\s+/g, " ").trim();
  if (text.length > 280) text = text.slice(0, 277).replace(/\s+\S*$/, "") + "…";
  return text;
}
const CAT_HINTS = [
  [/sensor|detector|indicator/i, "sensors"], [/switch|relay/i, "switching"],
  [/\b555\b|\b4017\b|\bic\b|timer|op-?amp/i, "ics"], [/security|alarm|laser/i, "security"],
  [/basics|introduction|what is/i, "basics"],
];
function guessCats(title) {
  return [...new Set(CAT_HINTS.filter(([re]) => re.test(title)).map(([, c]) => c))];
}

/* ----------------------------------------------------------- data sources */
async function fromFeed() {
  const xml = await fetchText(`https://www.youtube.com/feeds/videos.xml?channel_id=${CHANNEL_ID}`, { tries: 15 });
  const videos = parseFeed(xml);
  if (!videos.length) throw new Error("feed had no entries");
  return { source: "feed", videos, stats: await scrapeStats() };
}

// Best effort: the public channel page carries subscriber and view totals. Missing values are simply left out.
async function scrapeStats() {
  try {
    const html = await fetchText(`https://www.youtube.com/channel/${CHANNEL_ID}/about`, { tries: 2, headers: { Cookie: "CONSENT=YES+1" } });
    const stats = {};
    const subs = /"subscriberCountText":"([\d.,]+)\s*([KMB])?\s*subscribers?"/i.exec(html);
    if (subs) stats.subscribers = Math.round(parseFloat(subs[1].replace(/,/g, "")) * ({ K: 1e3, M: 1e6, B: 1e9 }[(subs[2] || "").toUpperCase()] || 1));
    const views = /"viewCountText":"([\d,]+)\s*views"/i.exec(html);
    if (views) stats.views = +views[1].replace(/,/g, "");
    return stats;
  } catch {
    return {};
  }
}

async function api(path, params) {
  const qs = new URLSearchParams({ ...params, key: API_KEY });
  const res = await fetch(`https://www.googleapis.com/youtube/v3/${path}?${qs}`, { headers: { "User-Agent": UA } });
  const body = await res.json().catch(() => ({}));
  // never log the request URL: it contains the key
  if (!res.ok) throw new Error(`YouTube API ${path}: HTTP ${res.status} ${body?.error?.errors?.[0]?.reason || body?.error?.status || ""}`.trim());
  return body;
}
async function playlistIds(playlistId) {
  const ids = [];
  let pageToken;
  do {
    const page = await api("playlistItems", { part: "contentDetails", playlistId, maxResults: "50", ...(pageToken ? { pageToken } : {}) });
    for (const it of page.items || []) ids.push(it.contentDetails.videoId);
    pageToken = page.nextPageToken;
  } while (pageToken && ids.length < 1000);
  return ids;
}
async function fromApi(previous) {
  const ch = (await api("channels", { part: "statistics,contentDetails", id: CHANNEL_ID })).items?.[0];
  if (!ch) throw new Error("YouTube API: channel not found");
  const stats = {};
  if (!ch.statistics.hiddenSubscriberCount && num(ch.statistics.subscriberCount) != null) stats.subscribers = +ch.statistics.subscriberCount;
  if (num(ch.statistics.viewCount) != null) stats.views = +ch.statistics.viewCount;
  if (num(ch.statistics.videoCount) != null) stats.videos = +ch.statistics.videoCount;

  const ids = await playlistIds(ch.contentDetails.relatedPlaylists.uploads);
  // "UUSH…" is the channel's auto-generated Shorts playlist.
  let shortIds = null;
  try {
    shortIds = new Set(await playlistIds("UUSH" + CHANNEL_ID.slice(2)));
  } catch (e) {
    warn(`Could not read the Shorts playlist (${e.message}); falling back to a per-video check.`);
  }

  const videos = [];
  for (let i = 0; i < ids.length; i += 50) {
    const batch = await api("videos", { part: "snippet,contentDetails,statistics", id: ids.slice(i, i + 50).join(","), maxResults: "50" });
    for (const v of batch.items || []) {
      if (v.snippet?.channelId !== CHANNEL_ID) continue; // only this channel's uploads
      let isShort;
      if (shortIds) isShort = shortIds.has(v.id);
      else if (previous[v.id]) isShort = previous[v.id].kind === "short";
      else isShort = await looksLikeShort(v.id);
      videos.push({
        id: v.id,
        rawTitle: v.snippet.title,
        description: v.snippet.description || "",
        date: (v.snippet.publishedAt || "").slice(0, 10),
        isShort,
        length: isoToLength(v.contentDetails?.duration),
        views: num(v.statistics?.viewCount),
        likes: num(v.statistics?.likeCount),
      });
    }
  }
  if (!videos.length) throw new Error("YouTube API returned no videos");
  return { source: "api", videos, stats };
}
// youtube.com/shorts/<id> answers 200 for a Short and redirects to /watch for a normal video.
async function looksLikeShort(id) {
  try {
    const res = await fetch(`https://www.youtube.com/shorts/${id}`, { method: "HEAD", redirect: "manual", headers: { "User-Agent": UA } });
    return res.status === 200;
  } catch {
    return false;
  }
}

/* ----------------------------------------------------------------- checks */
// Every fetched value passes a check before it may replace what the site already shows.
// A value that looks wrong is held back and remembered in `pending`; if a later run (on another
// day) reports the same thing again, it is treated as real and accepted. Glitches don't repeat,
// genuine changes (a deleted video, a retitled upload) do.
const TODAY = new Date().toISOString().slice(0, 10);
const report = { added: [], updated: 0, held: [], confirmed: [], skipped: [] };
let pendingIn = {};
const pendingOut = {};

const validId = (id) => typeof id === "string" && /^[\w-]{11}$/.test(id);
const validDate = (d) => /^\d{4}-\d{2}-\d{2}$/.test(d || "") && Date.parse(d) <= Date.now() + 864e5 && Date.parse(d) >= Date.parse("2005-01-01");
const sameEnough = (a, b) => (typeof a === "number" && typeof b === "number" ? Math.abs(a - b) <= Math.max(1, Math.abs(b) * 0.05) : a === b);

// Returns `next` if it is believable, otherwise `prev` (and remembers `next` for the next run).
function hold(key, label, next, prev, why) {
  const seen = pendingIn[key];
  if (seen && seen.date < TODAY && sameEnough(seen.value, next)) {
    report.confirmed.push(`${label}: ${prev} → ${next} (reported again, first seen ${seen.date})`);
    return next;
  }
  pendingOut[key] = { value: next, date: seen && sameEnough(seen.value, next) ? seen.date : TODAY };
  report.held.push(`${label}: kept ${prev}, ignored ${next} (${why})`);
  return prev;
}
function checkCount(key, label, next, prev, { maxDrop, maxRise } = {}) {
  if (!Number.isInteger(next) || next < 0) return prev; // missing or malformed: keep what we have
  if (typeof prev !== "number") return next;
  if (next < prev * (1 - maxDrop)) return hold(key, label, next, prev, `drop of more than ${Math.round(maxDrop * 100)}%`);
  if (maxRise && next > prev * maxRise && next - prev > 1000) return hold(key, label, next, prev, `more than ${maxRise}× the previous value`);
  return next;
}
function checkStats(fetched, prev = {}) {
  const out = { ...prev };
  let fresh = false;
  const rules = { subscribers: { maxDrop: 0.1, maxRise: 2 }, views: { maxDrop: 0.02, maxRise: 2 }, videos: { maxDrop: 0.5, maxRise: 3 } };
  for (const [k, rule] of Object.entries(rules)) {
    if (fetched[k] == null) continue;
    const v = checkCount(`stats.${k}`, `Channel ${k}`, fetched[k], prev[k], rule);
    if (v === fetched[k]) fresh = true;
    if (v != null) out[k] = v;
  }
  if (fresh) out.asOf = TODAY; // the date shown on the site only moves when numbers were really refreshed
  return out;
}

function buildItem(v, prev) {
  const label = `${v.id}`;
  if (!validId(v.id)) { report.skipped.push(`${String(v.id).slice(0, 20)}: not a valid video id`); return prev; }
  const { title, topic } = splitTitle(v.rawTitle || "", v.isShort);
  if (!title) { report.skipped.push(`${label}: empty title`); return prev; }
  const date = validDate(v.date) ? v.date : prev?.date;
  if (!date) { report.skipped.push(`${label} (${title}): no usable upload date`); return prev; }

  // A given upload never switches between Short and video, so a flip is suspicious.
  let kind = v.isShort ? "short" : "video";
  if (prev && prev.kind !== kind) kind = hold(`${v.id}:kind`, `${title} type`, kind, prev.kind, "type changed");
  const isShort = kind === "short";

  const item = { kind, title: isShort === v.isShort ? title : splitTitle(v.rawTitle, isShort).title };
  if (topic) item.topic = topic;
  item.date = prev?.date && validDate(prev.date) ? prev.date : date; // the upload date never changes once known
  const length = v.length || prev?.length;
  if (length) item.length = length;
  const views = checkCount(`${v.id}:views`, `${title} views`, v.views, prev?.views, { maxDrop: 0.1 });
  if (views != null) item.views = views;
  const likes = checkCount(`${v.id}:likes`, `${title} likes`, v.likes, prev?.likes, { maxDrop: 0.5 });
  if (likes != null) item.likes = likes;
  if (!isShort) {
    item.slug = prev?.slug || slugify(item.title);
    const summary = summarize(v.description || "") || prev?.summary;
    if (summary) item.summary = summary;
    // An emptied description shouldn't wipe a parts list we already have.
    const parts = parseParts(v.description || "") || prev?.parts;
    if (parts) item.parts = parts;
    const cats = guessCats(item.title);
    if (cats.length) item.cats = cats;
  }
  if (!prev) report.added.push(`${kind}: ${item.title} (${v.id})`);
  else if (JSON.stringify(prev) !== JSON.stringify(item)) report.updated++;
  return item;
}

/* ------------------------------------------------------------------- main */
async function readExisting() {
  try {
    const text = await readFile(OUT, "utf8");
    return JSON.parse(text.slice(text.indexOf("{", text.indexOf("window.AYJ_AUTO")), text.lastIndexOf("}") + 1));
  } catch {
    return { items: {} };
  }
}

// Everything except the numbers that drift every day.
function structure(data) {
  const items = {};
  for (const [id, it] of Object.entries(data.items || {})) {
    const { views, likes, ...rest } = it;
    items[id] = rest;
  }
  return JSON.stringify(items);
}
const withoutStamp = ({ updated, ...rest }) => JSON.stringify(rest);

async function summary(lines) {
  console.log(lines.join("\n"));
  if (process.env.GITHUB_STEP_SUMMARY) await appendFile(process.env.GITHUB_STEP_SUMMARY, lines.join("\n") + "\n");
}

async function main() {
  const existing = await readExisting();
  const previous = existing.items || {};
  pendingIn = existing.pending || {};

  let fetched;
  if (API_KEY) {
    try {
      fetched = await fromApi(previous);
    } catch (e) {
      warn(`${e.message}. Falling back to the public feed.`);
    }
  }
  if (!fetched) {
    try {
      fetched = await fromFeed();
    } catch (e) {
      warn(`Could not read the YouTube feed (${e.message}). Nothing was changed; the next scheduled run will try again.`);
      return;
    }
  }

  const items = { ...previous };
  for (const v of fetched.videos) {
    const item = buildItem(v, previous[v.id]);
    if (item) items[v.id] = item;
  }
  const sorted = Object.fromEntries(
    Object.entries(items).sort(([ia, a], [ib, b]) => (b.date || "").localeCompare(a.date || "") || ia.localeCompare(ib))
  );

  const next = { updated: TODAY, source: fetched.source, stats: checkStats(fetched.stats || {}, existing.stats), items: sorted };
  if (Object.keys(pendingOut).length) next.pending = pendingOut;

  const lines = [`### Update from YouTube (${fetched.source})`, `${fetched.videos.length} uploads read, ${Object.keys(sorted).length} known in total.`];
  if (report.added.length) lines.push("", "**New uploads**", ...report.added.map((l) => `- ${l}`));
  if (report.updated) lines.push("", `${report.updated} existing entr${report.updated === 1 ? "y" : "ies"} refreshed.`);
  if (report.confirmed.length) lines.push("", "**Unusual changes now accepted**", ...report.confirmed.map((l) => `- ${l}`));
  if (report.held.length) lines.push("", "**Held back (will be accepted if the next run agrees)**", ...report.held.map((l) => `- ${l}`));
  if (report.skipped.length) lines.push("", "**Skipped (bad data)**", ...report.skipped.map((l) => `- ${l}`));
  await summary(lines);
  for (const l of [...report.held, ...report.skipped]) warn(l);

  // Final guards: never write a file that lost entries or would not load.
  if (Object.keys(sorted).length < Object.keys(previous).length) throw new Error("Refusing to write: the new file would have fewer entries than the current one.");
  const body = `${HEADER}window.AYJ_AUTO = ${JSON.stringify(next, null, 2)};\n`;
  JSON.parse(body.slice(body.indexOf("{", body.indexOf("window.AYJ_AUTO")), body.lastIndexOf("}") + 1));

  const structural = structure(next) !== structure(existing);
  const ageDays = existing.updated ? (Date.parse(TODAY) - Date.parse(existing.updated)) / 864e5 : Infinity;
  if (!FORCE && withoutStamp(next) === withoutStamp(existing)) {
    console.log("Everything is already up to date. Nothing to commit.");
    return;
  }
  if (!FORCE && !structural && ageDays < STATS_REFRESH_DAYS) {
    console.log("No new uploads, and the numbers were already refreshed today. Nothing to commit.");
    return;
  }
  await writeFile(OUT, body, "utf8");
  console.log(`Wrote assets/js/latest.js (${structural ? "content changed" : "numbers refreshed"}).`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
